bash: cosmetic.

diff --git a/bin/zlib-git-repo b/bin/zlib-git-repo
--- a/bin/zlib-git-repo
+++ b/bin/zlib-git-repo
@@ -11,38 +11,40 @@ repo_list_deleted()    { git ls-files --deleted; }
 repo_list_unmerged()   { git diff --name-only --diff-filter=U --ignore-submodules | cut -f1; }
 
 repo_require_clean_work_tree () {
-    io_info >&2 "repo_require_clean_work_tree '$*'"
+    # io_info >&2 "repo_require_clean_work_tree"
+    local prefix="$*"
+    [[ -z $prefix ]] && prefix='error' || prefix="cannot $prefix"
     local err=0
 
     # Update the index
     if ! git update-index -q --ignore-submodules --refresh; then
-        io_error 'your have unmerged paths.'
-        io_message >&2 "$(repo_list_unmerged)" '' Red
-        io_message >&2 "fix conflicts and run 'git commit'." '' Yellow
+        io_error 'your have unmerged paths.' "$prefix"
+        io_message >&2 "$(repo_list_unmerged | sed 's/^/  /')" '' Red
+        io_message >&2 "  fix conflicts and run 'git commit'." '' Yellow
         err=1
     fi
 
     # Disallow untracked changes in the working tree
     if ! test -z "$(git ls-files --exclude-standard --others)"; then
-        io_error 'your work tree contains untracked changes.'
-        io_message >&2 "$(repo_list_untracked)" '' Red
-        io_message >&2 "run 'git add'" '' Yellow
+        io_error 'your work tree contains untracked changes.' "$prefix"
+        io_message >&2 "$(repo_list_untracked | sed 's/^/  /')" '' Red
+        io_message >&2 "  run 'git add'" '' Yellow
         err=1
     fi
 
     # Disallow unstaged changes in the working tree
     if ! git diff-files --quiet --ignore-submodules --; then
-        io_error 'you have unstaged changes.'
-        io_message >&2 "$(repo_list_unstaged)" '' Red
-        io_message >&2 "run 'git commit' or 'git stash'." '' Yellow
+        io_error 'you have unstaged changes.' "$prefix"
+        io_message >&2 "$(repo_list_unstaged | sed 's/^/  /')" '' Red
+        io_message >&2 "  run 'git stash' or 'git add' and 'git commit'." '' Yellow
         err=1
     fi
 
     # Disallow uncommitted changes in the index
     if ! git diff-index --cached --quiet HEAD --ignore-submodules --; then
-        io_error 'your index contains uncommitted changes.'
-        io_message >&2 "$(repo_list_uncommited)" '' Red
-        io_message >&2 "run 'git commit'." '' Yellow
+        io_error 'your index contains uncommitted changes.' "$prefix"
+        io_message >&2 "$(repo_list_uncommited | sed 's/^/  /')" '' Red
+        io_message >&2 "  run 'git commit'." '' Yellow
         err=1
     fi
 
