zoul: work out branch_move helper.

diff --git a/bin/zoul-git-branch-core b/bin/zoul-git-branch-core
--- a/bin/zoul-git-branch-core
+++ b/bin/zoul-git-branch-core
@@ -17,6 +17,10 @@ ZOUL_GIT_BRANCH_CORE=true
 
 branchChangedEvent=()
 branch_raise_branch_changed_event() { local handler; for handler in "${branchChangedEvent[@]}"; do $handler "$@"; done; }
+# out:
+# 0 -- success
+#   upstream -- upstream branch (event if local branch has been deleted)
+# 1 -- failure
 branch_upstream()
 {
   git rev-parse --abbrev-ref $1@{upstream} 2>/dev/null && return 0
@@ -325,19 +329,65 @@ branch_set_upstream()
 }
 branch_move()
 {
-  local branch1=$1 branch2=$2
-  [[ -z $branch1 || -z $branch2 ]] && { io_error "branch_move: missing argument[s]" "$moduleTracePrefix"; return 1; }
-  if git checkout $branch1 &>/dev/null; then
-    git checkout - &>/dev/null
-    git ls-remote --heads --exit-code origin "$branch1" &>/dev/null || git push origin "$branch1"
-    git branch "$branch2" "origin/$branch1" >/dev/null 2>&1
-    git push origin --set-upstream "$branch2" >/dev/null 2>&1
-    git push --delete --force origin "$branch1" >/dev/null 2>&1
-    git branch -D "$branch1" >/dev/null 2>&1
-    io_warning "Moved branch '$branch1' to '$branch2'" "$moduleTracePrefix"
-    return 0;
+  # io_trace "branch_move ${*@Q}"
+  local branch1=$1 branch2=$2 ec=0
+  [[ -z "$branch1" || -z "$branch2" ]] && { io_error "branch_move: missing argument[s]" "$moduleTracePrefix"; return 1; }
+  [[ $branch1 == 'master' ]] && { io_error "branch_move: branch 'master' cannot be renamed" "$moduleTracePrefix"; return 1; }
+  branch_exists "$branch2" && { io_error "branch_move: destination branch '$branch2' already exists" "$moduleTracePrefix"; return 1; }
+
+  branch1=$(branch_realize "$branch1"); ec=$?
+  if [ $ec -eq 0 ]; then
+    # local branch1 exists
+    rbranch1=$(branch_upstream "$branch1")
+    if [ $? -eq 0 ]; then
+      local remote=${rbranch1%%/*}
+      # io_trace "branch_move (RENAME BOTH) -- $(print_vars branch1 branch2 rbranch1 remote)"
+      # remote branch1 exists : rename both
+      local tmpBranch
+      if branch_is_current "$branch1"; then
+        tmpBranch='zou/branch_move'
+        if ! git checkout -b "$tmpBranch" "$branch1" &>/dev/null; then
+          git branch -D "$tmpBranch" >/dev/null 2>&1
+          repo_require_clean_work_tree 'Cannot move branch[es]'
+          return 1
+        fi
+      fi
+      # create branch2 at rbranch1
+      git branch "$branch2" "$rbranch1" >/dev/null 2>&1
+      # create remote branch2
+      git push -u "$remote" "$branch2" >/dev/null 2>&1
+      # delete remote branch1
+      git push --delete --force "$remote" "$branch1" >/dev/null 2>&1
+      # delete local branch1
+      git branch -D "$branch1" >/dev/null 2>&1
+      # restore active branch (renamed)
+      if [[ -n $tmpBranch ]]; then
+        branch_checkout "$branch2" >/dev/null 2>&1
+        git branch -D "$tmpBranch" >/dev/null 2>&1
+        git push --delete --force "$remote" "$tmpBranch" >/dev/null 2>&1
+      fi
+    else
+      # remote branch1 does not exist : rename local only
+      # io_trace "branch_move (RENAME LOCAL ONLY) -- $(print_vars branch1 branch2)"
+      git branch -m "$branch1" "$branch2"
+    fi 
+  elif [ $ec -eq 1 ]; then
+    # local branch1 does not exist : rename remote only
+    local remote=${branch1%%/*}
+    # io_trace "branch_move (RENAME REMOTE ONLY) -- $(print_vars branch1 branch2 remote)"
+    # create branch2 at rbranch1
+    git branch "$branch2" "$branch1" >/dev/null 2>&1
+    # create remote branch2
+    git push -u "$remote" "$branch2" >/dev/null 2>&1
+    # delete remote branch1
+    git push --delete --force "$remote" "${branch1#*/}" >/dev/null 2>&1
+    # delete local branch2
+    git branch -D "$branch2" >/dev/null 2>&1
+  else
+    io_error "branch_move: branch '$branch1' does not exist" "$moduleTracePrefix"
+    return 1
   fi
-  return 1
+  io_success "Moved branch '$branch1' to '$branch2'" "$moduleTracePrefix"
 }
 branch_set_hint_type()
 {
