zoul: redesign branch selection.

diff --git a/bin/zoul-git-branch-select b/bin/zoul-git-branch-select
--- a/bin/zoul-git-branch-select
+++ b/bin/zoul-git-branch-select
@@ -16,70 +16,52 @@ ZOUL_GIT_BRANCH_SELECT=true
 # in:
 #   $1: sku
 # out:
-#   bestMatch -- local or remote dev branch
-branch_best_match_dev()
+#   branch   -- local or remote
+#   lbranch  -- local branch
+# return:
+#   1 -- not found
+branch_set_best_match_dev()
 {
+  unset branch
   local patterns=$(ref_dev_fallback $1) \
         branches=( $(branch_list_local) ) \
         remoteIndex=${#branches[@]} \
-        pattern branch lbranch i
+        pattern b i
         
   branches+=( $(branch_list_remote_untracked) )
   # try to find a branch matching bundle branch name
   for pattern in $patterns; do
     for i in ${!branches[@]}; do
-      branch=${branches[i]}
-      (( $i < $remoteIndex )) && lbranch=$branch || lbranch=${branch#*/}
+      b=${branches[i]}
+      (( $i < $remoteIndex )) && lbranch=$b || lbranch=${b#*/}
       [[ $lbranch == $pattern ]] && {
-        echo $branch
+        branch=$b
         return 0
       }
     done
   done
+  unset lbranch
   return 1
-}
-branch_best_match_prod()
-{
-  local sku=$1 branch
-  branch=$(branch_realize $sku 2>/dev/null)
-  if [ $? -le 1 ]; then
-    echo $branch
-  else
-    vtag_get_vbranch_name $(vtag_describe $(branch_best_match_dev $sku))
-  fi
-}
-# in:
-#   $1: sku
-#   $2: hint (dev|prod)
-# out:
-#   bestMatch -- local or remote branch
-branch_best_match()
-{
-  # io_trace "branch_best_match ${*@Q}"
-  local sku=$1 hint=$2
-  if [[ $hint == 'prod' ]]; then
-    vtag_get_vbranch_name $(vtag_describe $(branch_best_match_dev $sku))
-  elif [[ $hint == 'dev' ]]; then
-    branch_best_match_dev $sku
-  else
-    if branch_is_prod $sku; then
-      branch_best_match_prod $sku
-    else
-      branch_best_match_dev $sku
-    fi
-  fi
 }
 # Create SKU selection information
 #
 # usage:
-#   local branch vbranch vtag htag delta alias status
+#   local branch lbranch vbranch vtag htag delta alias status
 #   branch_set_select_info $sku $skipVNodes $allowDuplicateTags
+#
+#                       skipVNodes allowDuplicateTags
+#   publish.submodule:    false        false 
+#      publish.bundle:    false        true 
+#    select.submodule:    true         false 
+#       select.bundle:    true         true 
+#
 # in:
 #   $1:sku=bundleBranch
-#   $2:skipVNodes=true          -- 
-#   $3:allowDuplicateTags=true
+#   $2:skipVNodes=true          -- false to publish,   true to select 
+#   $3:allowDuplicateTags=true  -- false in submodule, true in bundle
 # out:
-#   branch    -- best match branch
+#   branch    -- best match branch (local or remote)
+#   lbranch   -- local branch name
 #   vbranch   -- associated version branch
 #   vtag      -- nearest vtag (depends on skipVNodes value)
 #   htag      -- highest vtag on vbranch (depends on allowDuplicateTags value)
@@ -89,38 +71,39 @@ branch_best_match()
 #                vnodeOnly  -- nearest vtag is a vnode and there is no other vtag (branch was never published)
 #                vnode      -- nearest vtag is a vnode (branch was never published on this vbranch)
 #                vtag       -- nearest vtag is a vtag
-#                noVTag     -- no vtag found (branch was never published)
+#                vtagMissing     -- no vtag found (branch was never published)
 branch_set_select_info()
 {
+  unset vbranch vtag htag delta alias status
   local sku=${1:-$bundleBranch} skipVNodes=$2 allowDuplicateTags=$3 ltag ec=0
-  branch=$(branch_best_match_dev "$sku")
-  if ltag=$(vtag_describe "$branch" $skipVNodes); then
+  branch_set_best_match_dev "$sku"                   # -> branch lbranch
+  vtag_set_describe "$branch" "$lbranch" $skipVNodes # -> ltag
+  if [[ -n $ltag ]]; then
     # ZOU_TRACE=true io_trace "branch_set_select_info 1 -- $(print_vars sku skipVNodes allowDuplicateTags branch ltag)"
     vtag_set_info $ltag         # -> vtag delta alias
-    vtag_set_vbranch_name $vtag # -> vbranch
+    local folder version
+    vtag_set_vbranch_name $vtag # -> vbranch folder version
     htag=$(vtag_highest $vbranch true)
     if [[ $htag != $vtag ]]; then
-      git merge-base --is-ancestor "$branch" "$htag" >&2 || io_message "Branch '$branch' was never published as '$htag'" "$moduleTracePrefix" LightPurple
-      delta=$(( -$(git rev-list --count $vtag..$htag) + 1 ))
+      git merge-base --is-ancestor "$branch" "$htag" >&2 || io_message "Branch '$lbranch' was never published as '$htag'" "$moduleTracePrefix" LightPurple
+      delta=$(( -$(git rev-list --count $vtag..$htag) ))
       vtag=$htag
       alias="< $vtag ($delta)" # (master < v2.0.0 (8))
     fi
-    [ $delta -ne 0 ] && alias="$branch $alias" # (master > v2.0.0 (8))
+    [ $delta -ne 0 ] && alias="$lbranch $alias" # (master > v2.0.0 (8))
 
     if [[ $allowDuplicateTags != true ]]; then
       htag=$(vtag_highest $vbranch false)
     fi
+    # vnode or vtag
     if vtag_is_vnode $vtag; then
-      local vtags=( $(vtag_list "$vbranch" | grep -v '\-@$') )
-      if [ ${#vtags[@]} -eq 0 ]; then
-        status='vnodeOnly'
-      else
-        status='vnode'
-      fi
+      git tag -l "${folder}v${version}*" | grep -v '\-@$' \
+      && status='vnode' \
+      || status='vnodeOnly'
     else
       status='vtag'
     fi
-    # ZOU_TRACE=true io_trace "branch_set_select_info 2 -- $(print_vars sku skipVNodes allowDuplicateTags branch vbranch vtag delta alias status)"
+    # ZOU_TRACE=true io_trace "branch_set_select_info 2 -- $(print_vars sku skipVNodes allowDuplicateTags branch lbranch vbranch vtag htag delta alias status)"
   else
     if [[ $skipVNodes == true ]]; then
       # compute alias without skipping vnodes
@@ -131,99 +114,98 @@ branch_set_select_info()
       alias='<>'
     fi
     unset vbranch vtag htag delta
-    status='noVTag'
-    # ZOU_TRACE=true io_trace "branch_set_select_info 3 -- $(print_vars sku skipVNodes allowDuplicateTags branch vbranch vtag delta alias status)"
+    status='vtagMissing'
+    # ZOU_TRACE=true io_trace "branch_set_select_info 3 -- $(print_vars sku skipVNodes allowDuplicateTags branch lbranch vbranch vtag htag delta alias status)"
   fi
 }
-# Select branch or vtag
-#   if module == bundle || hint == dev
-#     select dev branch
-#   else
-#     select vtag
+# Select branch or vtag and return status for publish
+#
+# usage:
+#  local branch vbranch vtag htag publishStatus
+#  branch_set_select_auto $sku $hint $forceCheckout $skipVNodes $allowDuplicateTags
 #
 # in:
-#   $1:sku=bundleBranch
+#   $1:sku
 #   $2:hint -- hint == dev ? select dev branch : select vtag
-#   $2:forceCheckout=true
+#   $3:forceCheckout=true
+#   $4:skipVNodes=true
+#   $5:allowDuplicateTags=true
 # out:
-#   branchOrTag -- selected branch or vtag
-#
-#   0:devBranch,        branch -- switch to dev branch
-#   1:noVTag,           branch -- switch to dev branch
-#   2:vnodeOnly,        branch -- switch to dev branch (nearest vtag is a vnode)
-#   3:vnode,            branch -- switch to dev branch (nearest vtag is a vnode)
-#   4:alreadyPublished, vtag   -- switch to dev branch (vtag == branch)
-#   5:ffPublish,        vtag   -- no change (vtag > branch)
-#  10:error
+#   branch
+#   vbranch
+#   vtag
+#   htag
+#   publishStatus
+#     vtagMissing
+#     published
+#     notPublished
+#     neverPublished
+#     ffPublish
 branch_set_select_auto()
 {
-  local sku=$1 hint=$2 forceCheckout=${3:-true} skipVNodes=${4:-true} allowDuplicateTags=$5 mroot broot ec=0
+  unset publishStatus branchOrTag
+
+  local sku=$1 hint=$2 forceCheckout=${3:-true} skipVNodes=${4:-true} allowDuplicateTags=${5:-true} ec=0
   [[ -z $sku ]]   && sku=$bundleBranch
   [[ -z $sku ]]   && sku=$(branch_current_root_branch)
-  [[ -z $mroot ]] && mroot=$moduleRoot
-  [[ -z $mroot ]] && mroot=$(repo_module_root)
-  [[ -z $broot ]] && broot=$bundleRoot
-  [[ -z $broot ]] && broot=$(repo_bundle_root)
-  [[ -z $allowDuplicateTags && $mroot == $broot ]] && allowDuplicateTags=true
 
   # ZOU_TRACE=true io_trace "branch_set_select_auto 1 -- $(print_vars sku hint forceCheckout skipVNodes allowDuplicateTags mroot broot)"
 
-  local branch vbranch vtag htag delta alias status
-  _branch_set_select_auto_core "$sku" "$hint" "$forceCheckout" "$skipVNodes" "$allowDuplicateTags" "$mroot" "$broot"  || ec=$?
+  local lbranch delta alias status
+  _branch_set_select_auto_core "$sku" "$hint" "$forceCheckout" "$skipVNodes" "$allowDuplicateTags" || ec=$?
 
-  # ZOU_TRACE=true io_trace "branch_set_select_auto 1 -- $(print_vars branch vbranch vtag htag alias status ec)"
+  # ZOU_TRACE=true io_trace "branch_set_select_auto 2 -- $(print_vars branch vbranch vtag htag alias status publishStatus ec)"
 
-  if [ $ec -eq 10 ]; then
+  if [ $ec -ne 0 ]; then
     repo_require_clean_work_tree "Cannot switch to '$branch'"
   else
     branch_set_upstream "$branch"
   fi
   return $ec
 }
+# in:
+#   sku hint forceCheckout skipVNodes allowDuplicateTags
+# out:
+#   branch vbranch vtag htag publishStatus
 _branch_set_select_auto_core()
 {
-  branch_set_select_info "$sku" "$skipVNodes" "$allowDuplicateTags"
-
-  if [[ "$mroot" == "$broot" || $hint == 'dev' ]]; then
-    # force dev branch
-    branch_checkout "$branch" "$forceCheckout" "$alias" >/dev/null || return 10
-    branchOrTag=$branch
-    return 0 # switched to dev branch
-  elif [[ $status == 'noVTag' ]]; then
+  branch_set_select_info "$sku" "$skipVNodes" "$allowDuplicateTags" # -> branch lbranch vbranch vtag htag delta alias status
+  publishStatus=$status
+  branch=$lbranch # work with local branch name
+  if [[ $status == 'vtagMissing' ]]; then
     # no vtag, stay in dev mode
-    branch_checkout "$branch" "$forceCheckout" "$alias" || return 10
-    branchOrTag=$branch
-    return 1  # never published
-  elif [[ $status == 'vnodeOnly' ]]; then
-    # preview mode, stay in dev mode
-    branch_checkout "$branch" "$forceCheckout" "$alias" || return 10
-    branchOrTag=$vtag
-    return 2  # vnode only
-  elif [[ $status == 'vnode' ]]; then
-    # preview mode, stay in dev mode
-    branch_checkout "$branch" "$forceCheckout" "$alias" || return 10
-    branchOrTag=$vtag
-    return 3  # vnode
+    branch_checkout "$branch" "$forceCheckout" "$alias" || return 1
+    publishStatus='vtagMissing'
   elif [[ $status == 'vtag' ]]; then
     # already published
-    if [ $delta -gt 0 ]; then
-      # dev == prod (branch == vtag)
-      branch_checkout "$vtag" "$forceCheckout" "$alias" || return 10
-      branchOrTag=$vtag
-      return 4  # already published
-    elif [ $delta -eq 0 ]; then
-      # dev == prod (branch == vtag)
-      branch_try_attach "$vtag" "$branch" "$forceCheckout" "$alias" || return 10
-      branchOrTag=$vtag
-      return 4  # already published
+    if [ $delta -eq 0 ]; then
+      branch_checkout "$branch" "$forceCheckout" "$alias" || return 1
+      publishStatus='published'
+    elif [ $delta -gt 0 ]; then
+      # branch > vtag
+      [[ $hint == 'dev' ]] && ref=$branch || ref=$vtag
+      branch_checkout "$ref" "$forceCheckout" "$alias" || return 1
+      publishStatus='notPublished'
     elif [ $delta -lt 0 ]; then
-      branch_checkout "$vtag" "$forceCheckout" "$alias" || return 10
-      branchOrTag=$vtag
-      return 5  # vtag is more recent
+      # branch < vtag
+      [[ $hint == 'dev' ]] && ref=$branch || ref=$vtag
+      branch_checkout "$ref" "$forceCheckout" "$alias" || return 1
+      publishStatus='ffPublish'
     else
       io_error "_branch_set_select_auto_core: delta '$delta' not implemented" "$moduleTracePrefix"
+      return 1
     fi
   else
-    io_error "_branch_set_select_auto_core: status '$status' not implemented" "$moduleTracePrefix"
+    branch_checkout "$branch" "$forceCheckout" "$alias" || return 1
+    if [[ $status == 'vnodeOnly' ]]; then
+      # preview mode, stay in dev mode
+      publishStatus='neverPublished'
+    elif [[ $status == 'vnode' ]]; then
+      # preview mode, stay in dev mode
+      publishStatus='notPublished'
+    else
+      io_error "_branch_set_select_auto_core: status '$status' not implemented" "$moduleTracePrefix"
+      return 1
+    fi
   fi
 }
