zou-flow: repair previous git hooks configuration...
- the hooks directory was polluted when the file name expansion was not enabled

diff --git a/bin/zoul-git-hooks b/bin/zoul-git-hooks
--- a/bin/zoul-git-hooks
+++ b/bin/zoul-git-hooks
@@ -28,11 +28,29 @@ hooks_update_module()
   # io_trace "hooks_update_module -2- $(print_vars srcDir dstDir)"
 
   # setup multi-hooks
-  for srcPath in $srcDir/*; do
+  set +f # enable file name expansion
+  for srcPath in "$srcDir"/*; do
+    [ -e $srcPath ] || continue
     _hooks_update_hook "$srcPath" "$dstDir" "$force" || equals=1
   done
-  
+  set -f
+
   return $equals
+}
+# return code:
+#   0 : not broken
+#   1 : repaired
+hooks_repair()
+{
+  local dstDir="$(git_dir "${1:-$moduleRoot}")/hooks" ec=0
+  # fix previous zou versions
+  set -f # disable file name expansion
+  if [[ -d "$dstDir/*.d" ]]; then
+    rm -rf "$dstDir/*.d"
+    rm "$dstDir/*"
+    ec=1
+  fi
+  return $ec
 }
 
 # in:
@@ -44,6 +62,8 @@ hooks_update_module()
 #   1 : source hook != destination hook || destination hook does not exist
 _hooks_update_hook()
 {
+  # io_trace "_hooks_update_hook ${*@Q}"
+
   local srcPath="$1" dstDir="$2" force=$3 hookName hookDir hookFolder original
   hookName="$(basename "$srcPath")"
   hookFolder="${hookName}.d"
