zoul: enhance selection process.
- if highest vtag is on a separate branch retry without skipping vnodes
- if no vnodes are found, display a warning message

diff --git a/bin/zoul-git-branch-select b/bin/zoul-git-branch-select
--- a/bin/zoul-git-branch-select
+++ b/bin/zoul-git-branch-select
@@ -74,9 +74,10 @@ branch_set_best_match_dev()
 branch_set_select_info()
 {
   unset branch lbranch vbranch vtag htag delta alias status
-  local sku=${1:-$bundleBranch} skipVNodes=$2 allowDuplicateTags=$3 ltag ec=0
+  local sku=${1:-$bundleBranch} skipVNodes=$2 allowDuplicateTags=$3 skip=${2:-true} ltag ec=0
+  # io_trace "branch_set_select_info ${*@Q}"
   branch_set_best_match_dev "$sku"                   # -> branch lbranch
-  vtag_set_describe "$branch" "$lbranch" $skipVNodes # -> ltag
+  vtag_set_describe "$branch" "$lbranch" "$skip" # -> ltag
   # io_trace "branch_set_select_info 1 -- $(print_vars sku skipVNodes allowDuplicateTags branch lbranch ltag alias)"
   if [[ -n $ltag ]]; then
     vtag_set_info $ltag         # -> vtag delta alias
@@ -84,8 +85,17 @@ branch_set_select_info()
     vtag_set_vbranch_name $vtag # -> vbranch folder version
     htag=$(vtag_highest $vbranch true)
     if [[ $htag != $vtag ]]; then
-      git merge-base --is-ancestor "$branch" "$htag" >&2 || io_message "Branch '$lbranch' was never published as '$htag'" "$moduleTracePrefix" LightPurple
+      if ! git merge-base --is-ancestor "$branch" "$htag" >&2; then
+        # retry without skipping vnodes
+        if [[ -z $skipVNodes && $skip == true ]]; then
+          branch_set_select_info "$sku" false "$allowDuplicateTags"
+          return $?
+        else
+          io_message "Branch '$lbranch' was never published as '$htag'" "$moduleTracePrefix" LightPurple
+        fi
+      fi
       delta=$(( -$(git rev-list --count $vtag..$htag) ))
+      # io_trace "branch_set_select_info 2 -- $(print_vars sku skipVNodes allowDuplicateTags branch lbranch vbranch ltag vtag htag delta alias status)"
       vtag=$htag
       alias="< $vtag ($delta)" # (master < v2.0.0 (8))
     fi
@@ -96,17 +106,17 @@ branch_set_select_info()
     fi
     # vnode or vtag
     vtag_is_vnode $vtag && status='vnode' || status='vtag'
-    # io_trace "branch_set_select_info 2 -- $(print_vars sku skipVNodes allowDuplicateTags branch lbranch vbranch vtag htag delta alias status)"
+    # io_trace "branch_set_select_info 3 -- $(print_vars sku skipVNodes allowDuplicateTags branch lbranch vbranch ltag vtag htag delta alias status)"
   else
     # compute alias without skipping vnodes
-    if [[ $skipVNodes == true ]] && ltag=$(vtag_describe "$branch" false) && vtag_set_info $ltag; then
+    if [[ $skip == true ]] && ltag=$(vtag_describe "$branch" false) && vtag_set_info $ltag; then
       [ $delta -ne 0 ] && alias="$branch $alias" # (master > v2.0.0 (8))
     else
       alias='<>'
     fi
     unset vbranch vtag htag delta
     status='vtagMissing'
-    # io_trace "branch_set_select_info 3 -- $(print_vars sku skipVNodes allowDuplicateTags branch lbranch vbranch vtag htag delta alias status)"
+    # io_trace "branch_set_select_info 4 -- $(print_vars sku skipVNodes allowDuplicateTags branch lbranch vbranch vtag htag delta alias status)"
   fi
 }
 branch_ensure_attached()
@@ -143,7 +153,7 @@ branch_set_select_auto()
 {
   unset branch vbranch vtag htag publishStatus
 
-  local sku=$1 forceDev=${2:-false} forceCheckout=${3:-true} skipVNodes=${4:-true} allowDuplicateTags ec=0
+  local sku=$1 forceDev=${2:-false} forceCheckout=${3:-true} skipVNodes allowDuplicateTags ec=0
 
   [[ -z $sku ]]   && sku=$bundleBranch
   [[ -z $sku ]]   && sku=$(branch_current_root_branch)
